name: getitease
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  firebase_app_check: ^0.3.2+5
  firebase_auth: ^5.5.0
  cloud_firestore: ^5.6.4
  timeago: ^3.7.0
  intl: ^0.19.0
  image_picker: ^1.1.2
  image_cropper: ^9.0.0
  fluttertoast: ^8.2.12
  firebase_storage: ^12.4.3
  flutter_image_slider: ^0.0.2
  flutter_svg: ^2.0.17
  geolocator: ^14.0.0
  geocoding: ^3.0.0
  url_launcher: ^6.3.1
  map_launcher: ^3.5.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/images/logo.png
    - assets/images/images/logo_one.png
    - "assets/images/images/main_top.png"
    - "assets/images/images/main_bottom.png"
    - assets/images/images/login_bottom.png
    - 'assets/icons/icons/login.png'
    - assets/images/images/logo_three.png
    - 'assets/images/images/default_profile.png'
